export function getThemeVars(isDark) {
  if (isDark) {
    return {
      "--page-bg": "#0f1720",
      "--login-bg": "linear-gradient(135deg, #0f1720, #111827)",
      "--text-main": "#f3f4f6",
      "--text-soft": "#d1d5db",
      "--text-muted": "#94a3b8",
      "--brand-text": "#f9fafb",
      "--brand-accent": "#26b1c4",
      "--card-bg": "#111827",
      "--card-bg-soft": "#162131",
      "--card-bg-alt": "#1d2939",
      "--module-bg": "#162131",
      "--input-bg": "#1d2939",
      "--input-border": "#314155",
      "--input-text": "#f3f4f6",
      "--border-soft": "rgba(148, 163, 184, 0.2)",
      "--header-bg": "rgba(17, 24, 39, 0.92)",
      "--header-box-bg": "rgba(29, 41, 57, 0.96)",
      "--tab-bg": "#162131",
      "--tab-text": "#dbe4ea",
      "--tab-border": "rgba(148, 163, 184, 0.18)",
      "--tab-active-bg": "#26b1c4",
      "--tab-active-text": "#ffffff",
      "--primary-btn": "#26b1c4",
      "--primary-btn-text": "#ffffff",
      "--outline-bg": "#1d2939",
      "--outline-text": "#e5e7eb",
      "--outline-border": "rgba(148, 163, 184, 0.24)",
      "--danger-text": "#fecaca",
      "--danger-border": "rgba(239, 68, 68, 0.35)",
      "--info-pill-bg": "rgba(38, 177, 196, 0.16)",
      "--info-pill-text": "#8be0eb",
      "--status-bg": "rgba(38, 177, 196, 0.16)",
      "--status-text": "#8be0eb",
      "--status-border": "rgba(38, 177, 196, 0.22)",
      "--placeholder-bg": "#1d2939",
      "--shadow-main": "0 10px 30px rgba(0,0,0,0.22)",
    };
  }
  return {
    "--page-bg": "#f4f7f6",
    "--login-bg": "linear-gradient(135deg, #f4f7f6, #eef4f3)",
    "--text-main": "#333333",
    "--text-soft": "#4b5563",
    "--text-muted": "#666666",
    "--brand-text": "#333333",
    "--brand-accent": "#26b1c4",
    "--card-bg": "#ffffff",
    "--card-bg-soft": "#ffffff",
    "--card-bg-alt": "#f9fbfb",
    "--module-bg": "#ffffff",
    "--input-bg": "#f8fbfb",
    "--input-border": "#d9e4e2",
    "--input-text": "#333333",
    "--border-soft": "#e5ecea",
    "--header-bg": "rgba(255,255,255,0.88)",
    "--header-box-bg": "#ffffff",
    "--tab-bg": "#ffffff",
    "--tab-text": "#5c6670",
    "--tab-border": "#dfe8e6",
    "--tab-active-bg": "#26b1c4",
    "--tab-active-text": "#ffffff",
    "--primary-btn": "#26b1c4",
    "--primary-btn-text": "#ffffff",
    "--outline-bg": "#ffffff",
    "--outline-text": "#333333",
    "--outline-border": "#dfe8e6",
    "--danger-text": "#dc2626",
    "--danger-border": "rgba(220, 38, 38, 0.18)",
    "--info-pill-bg": "rgba(38, 177, 196, 0.1)",
    "--info-pill-text": "#1d7f8f",
    "--status-bg": "rgba(38, 177, 196, 0.1)",
    "--status-text": "#1d7f8f",
    "--status-border": "rgba(38, 177, 196, 0.18)",
    "--placeholder-bg": "#ffffff",
    "--shadow-main": "0 10px 30px rgba(0,0,0,0.05)",
  };
}

export const styles = {
  page: { minHeight: "100vh", background: "var(--page-bg)", fontFamily: 'Inter, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif', padding: 24, color: "var(--text-main)" },
  loginPage: { minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center", background: "var(--login-bg)", padding: 24, fontFamily: 'Inter, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif' },
  loginCard: { width: "100%", maxWidth: 450, background: "var(--card-bg-soft)", borderRadius: 24, padding: 36, boxShadow: "var(--shadow-main)", border: "1px solid var(--border-soft)" },
  loginBrandWrap: { textAlign: "center", marginBottom: 22 },
  loginLogo: { width: 220, maxWidth: "100%", display: "block", margin: "0 auto 14px", objectFit: "contain" },
  loginTitle: { textAlign: "center", margin: 0, color: "var(--text-main)", fontSize: 28, fontWeight: 800, letterSpacing: 0.4 },
  loginSub: { textAlign: "center", marginTop: 8, color: "var(--text-muted)", marginBottom: 22, fontSize: 14 },
  headerWrap: { marginBottom: 16 },
  headerBox: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, flexWrap: "wrap" },
  brandTitle: { fontSize: 22, fontWeight: 800 },
  brandSub: { fontSize: 14, color: "var(--text-muted)" },
  buttonIcon: { marginRight: 8 },
  tabs: { display: "flex", gap: 10, marginBottom: 18, flexWrap: "wrap" },
  tab: { padding: "12px 16px", borderRadius: 14, border: "1px solid var(--tab-border)", background: "var(--tab-bg)", cursor: "pointer", fontWeight: 700, color: "var(--tab-text)", boxShadow: "var(--shadow-main)" },
  tabActive: { padding: "12px 16px", borderRadius: 14, border: "1px solid var(--tab-active-bg)", background: "var(--tab-active-bg)", cursor: "pointer", fontWeight: 700, color: "var(--tab-active-text)", boxShadow: "0 10px 24px rgba(38, 177, 196, 0.24)" },
  grid2: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 18, marginBottom: 18 },
  grid2Simple: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 14 },
  grid3: { display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 14 },
  card: { background: "var(--card-bg-soft)", borderRadius: 24, padding: 24, boxShadow: "var(--shadow-main)", border: "1px solid var(--border-soft)", marginBottom: 18 },
  cardTitle: { marginTop: 0, color: "var(--text-main)", marginBottom: 16, fontSize: 24, fontWeight: 800 },
  sectionToggle: { width: "100%", border: "none", background: "transparent", display: "flex", alignItems: "center", justifyContent: "space-between", padding: 0, marginBottom: 18, cursor: "pointer", textAlign: "left" },
  sectionToggleIcon: { fontSize: 22, lineHeight: 1, color: "var(--brand-accent)", fontWeight: 700, minWidth: 24, textAlign: "center" },
  field: { display: "flex", flexDirection: "column", gap: 8, marginBottom: 14 },
  fieldWide: { display: "flex", flexDirection: "column", gap: 8, marginBottom: 14 },
  label: { fontSize: 12, fontWeight: 700, color: "var(--text-soft)", textTransform: "uppercase", letterSpacing: 0.6 },
  input: { border: "1px solid var(--input-border)", borderRadius: 12, padding: "12px 14px", fontSize: 14, outline: "none", background: "var(--input-bg)", color: "var(--input-text)", width: "100%", boxSizing: "border-box", transition: "border-color 0.2s ease, box-shadow 0.2s ease", boxShadow: "inset 0 1px 2px rgba(15, 23, 42, 0.02)" },
  primaryBtn: { background: "var(--primary-btn)", color: "var(--primary-btn-text)", border: "none", padding: "12px 18px", borderRadius: 14, cursor: "pointer", fontWeight: 700, boxShadow: "0 10px 24px rgba(38, 177, 196, 0.22)" },
  outlineBtn: { background: "var(--outline-bg)", color: "var(--outline-text)", border: "1px solid var(--outline-border)", padding: "11px 14px", borderRadius: 14, cursor: "pointer", fontWeight: 700, boxShadow: "var(--shadow-main)" },
  outlineDarkBtn: { background: "var(--outline-bg)", color: "var(--outline-text)", border: "1px solid var(--outline-border)", padding: "11px 14px", borderRadius: 14, cursor: "pointer", fontWeight: 700, boxShadow: "var(--shadow-main)" },
  outlineDangerBtn: { background: "var(--outline-bg)", color: "var(--danger-text)", border: "1px solid var(--danger-border)", padding: "11px 14px", borderRadius: 14, cursor: "pointer", fontWeight: 700 },
  errorBox: { marginBottom: 12, padding: 12, background: "rgba(254, 226, 226, 0.9)", color: "var(--danger-text)", borderRadius: 12, border: "1px solid var(--danger-border)" },
  separator: { height: 1, background: "var(--border-soft)", margin: "12px 0 18px" },
  infoRow: { display: "flex", gap: 10, flexWrap: "wrap", marginBottom: 14 },
  infoPill: { background: "var(--info-pill-bg)", border: "1px solid var(--status-border)", borderRadius: 999, padding: "8px 12px", fontSize: 13, fontWeight: 700, color: "var(--info-pill-text)" },
  helpText: { fontSize: 12, color: "var(--brand-accent)" },
  errorText: { fontSize: 12, color: "#dc2626" },
  row: { display: "flex", gap: 10 },
  listItem: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 10, border: "1px solid var(--border-soft)", background: "var(--card-bg-soft)", borderRadius: 16, padding: 14, marginBottom: 10, boxShadow: "var(--shadow-main)" },
  moduleCard: { background: "var(--module-bg)", borderRadius: 24, padding: 24, boxShadow: "var(--shadow-main)", marginBottom: 24, border: "1px solid var(--border-soft)" },
  moduleHeader: { display: "flex", justifyContent: "space-between", gap: 16, alignItems: "center", flexWrap: "wrap", marginBottom: 22 },
  moduleTitle: { margin: 0, color: "var(--text-main)", fontSize: 28, fontWeight: 800 },
  moduleSub: { margin: "6px 0 0", color: "var(--text-muted)", fontSize: 14 },
  modulePlaceholder: { background: "var(--card-bg-alt)", borderRadius: 22, padding: 28, minHeight: 220, display: "flex", flexDirection: "column", justifyContent: "center", border: "1px solid var(--border-soft)" },
  modulePlaceholderTitle: { color: "var(--text-main)", fontSize: 24, fontWeight: 800, marginBottom: 10 },
  modulePlaceholderText: { color: "var(--text-muted)", fontSize: 15, lineHeight: 1.6, maxWidth: 780 },
  searchRow: { display: "flex", gap: 12, marginBottom: 14 },
  recordsList: { display: "flex", flexDirection: "column", gap: 14 },
  recordCard: { background: "var(--card-bg-soft)", border: "1px solid var(--border-soft)", borderRadius: 20, padding: 20, boxShadow: "var(--shadow-main)" },
  recordTop: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 12, marginBottom: 12, flexWrap: "wrap" },
  recordNumber: { fontSize: 12, fontWeight: 700, color: "var(--brand-accent)", marginBottom: 4, textTransform: "uppercase", letterSpacing: 0.8 },
  recordName: { fontSize: 20, fontWeight: 800, color: "var(--text-main)", marginBottom: 4 },
  recordMeta: { fontSize: 13, color: "var(--text-muted)" },
  recordGrid: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: 10, color: "var(--text-soft)", fontSize: 14, marginBottom: 14 },
  recordActions: { display: "flex", gap: 10, flexWrap: "wrap" },
  statusBadge: { background: "var(--status-bg)", color: "var(--status-text)", border: "1px solid var(--status-border)", borderRadius: 999, padding: "8px 12px", fontSize: 12, fontWeight: 700 },
  operationalCard: { background: "var(--card-bg-soft)", border: "1px solid var(--border-soft)", borderRadius: 20, padding: 20, boxShadow: "var(--shadow-main)" },
  operationalHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, flexWrap: "wrap", marginBottom: 10 },
  operationGrid: { display: "grid", gap: 12 },
  operationRow: { background: "var(--card-bg-alt)", border: "1px solid var(--border-soft)", borderRadius: 18, padding: 16, display: "grid", gridTemplateColumns: "minmax(180px, 1.1fr) minmax(140px, 0.8fr) minmax(260px, 1.2fr) auto", gap: 12, alignItems: "center" },
  operationMain: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" },
  operationName: { color: "var(--text-main)", fontSize: 16, fontWeight: 800 },
  operationStatusBase: { borderRadius: 999, padding: "8px 12px", fontWeight: 700, fontSize: 12, border: "1px solid transparent" },
  operationStatusWaiting: { background: "#f3f4f6", color: "#6b7280", borderColor: "#e5e7eb" },
  operationStatusRunning: { background: "rgba(38, 177, 196, 0.12)", color: "#1d7f8f", borderColor: "rgba(38, 177, 196, 0.2)" },
  operationStatusDone: { background: "rgba(34, 197, 94, 0.12)", color: "#15803d", borderColor: "rgba(34, 197, 94, 0.18)" },
  operationTimes: { display: "grid", gap: 4, color: "var(--text-muted)", fontSize: 13 },
  operationTransportGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10, alignItems: "end" },
  operationResponsibleGrid: { display: "grid", gridTemplateColumns: "1fr", gap: 10, alignItems: "end" },
  operationActions: { display: "flex", gap: 8, flexWrap: "wrap", justifyContent: "flex-end" },
  modalOverlay: { position: "fixed", inset: 0, background: "rgba(15, 23, 42, 0.5)", padding: 20, display: "flex", alignItems: "center", justifyContent: "center", zIndex: 999 },
  modalBox: { width: "100%", maxWidth: 1150, maxHeight: "90vh", overflowY: "auto", background: "var(--card-bg-soft)", borderRadius: 24, padding: 22, boxShadow: "0 24px 64px rgba(15, 23, 42, 0.16)", border: "1px solid var(--border-soft)" },
  modalHead: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, marginBottom: 16 },
  servicesGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 14 },
  serviceCard: { border: "1px solid var(--border-soft)", borderRadius: 18, padding: 16, background: "var(--card-bg-alt)", boxShadow: "var(--shadow-main)" },
  serviceTop: { marginBottom: 12 },
  previewOverlay: { position: "fixed", inset: 0, background: "rgba(15, 23, 42, 0.62)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 9999, padding: 20 },
  previewModal: { width: "100%", maxWidth: 1100, height: "90vh", background: "var(--card-bg)", border: "1px solid var(--border-soft)", borderRadius: 24, boxShadow: "0 28px 80px rgba(15, 23, 42, 0.24)", display: "flex", flexDirection: "column", overflow: "hidden" },
  previewHeader: { padding: 16, borderBottom: "1px solid var(--border-soft)", display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, flexWrap: "wrap" },
  previewFrame: { width: "100%", height: "100%", border: "none", background: "#fff" },
};
